name: quapred
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.2.2
  - cudnn=8.2.1.32
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1k
  - pip=21.2.2
  - python=3.7.11
  - python_abi=3.7
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.15.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - astunparse==1.6.3
    - async-timeout==4.0.1
    - asynctest==0.13.0
    - attrs==21.2.0
    - bio-transformers==0.1.16
    - biopython==1.79
    - boto3==1.20.15
    - botocore==1.23.15
    - bravado==11.0.3
    - bravado-core==5.17.0
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.8
    - cycler==0.11.0
    - deepchain-apps==0.1.10
    - deprecated==1.2.13
    - fair-esm==0.4.0
    - filelock==3.4.0
    - flatbuffers==1.12
    - fonttools==4.28.5
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==2.10.0
    - huggingface-hub==0.0.8
    - idna==3.3
    - importlib-metadata==4.8.2
    - importlib-resources==5.4.0
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonpointer==2.2
    - jsonref==0.2
    - jsonschema==3.2.0
    - keras==2.7.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==12.0.0
    - markdown==3.3.6
    - matplotlib==3.4.1
    - mlxtend==0.19.0
    - monotonic==1.6
    - msgpack==1.0.3
    - multidict==5.2.0
    - neptune-client==0.13.3
    - neptune-tensorflow-keras==0.9.9
    - numpy==1.18.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.4
    - pillow==8.4.0
    - protlearn==0.0.3
    - protobuf==3.19.1
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyjwt==2.3.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytorch-lightning==1.5.3
    - pytz==2021.3
    - pyyaml==6.0
    - ray==1.8.0
    - redis==4.0.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rfc3987==1.3.8
    - rsa==4.8
    - s3transfer==0.5.0
    - sacremoses==0.0.46
    - scikeras==0.4.1
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - simplejson==3.17.6
    - six==1.15.0
    - smmap==5.0.0
    - strict-rfc3339==0.7
    - swagger-spec-validator==2.7.4
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - torch==1.8.1
    - torchmetrics==0.4.1
    - tqdm==4.62.3
    - transformers==4.6.1
    - typing-extensions==4.0.0
    - urllib3==1.26.7
    - webcolors==1.11.1
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - xgboost==1.5.1
    - yarl==1.7.2

